[tool.poetry]
name = "lora-pytorch"
version = "0.1.0"
description = ""
authors = ["Alexandru Vesa"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
torch = "^2.1.1"
torchvision = "^0.16.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
